/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Dimension;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ScrollPaneConstants;

import controller.FingerprintController;
import model.CourseGroup;

/**
 *
 * @author D2D
 */
public class FingerprintForm extends javax.swing.JFrame {
    
    private FingerprintController fingerprintController;

    /**
     * Creates new form Fingerprint
     */
    public FingerprintForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Appear in middle of screen
        this.txtAreaHistory.setWrapStyleWord(true);
        this.scrollHistory.setPreferredSize(new Dimension(296, 84));
        this.scrollHistory.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        this.scrollHistory.setViewportView(this.txtAreaHistory);
        this.btnStop.setEnabled(false);
        this.btnSave.setEnabled(false);
        //this.btnIdentify.setEnabled(false);
        this.btnRegisterAssistance.setEnabled(false);
        this.btnRegisterParticipation.setEnabled(false);
    }

    public void setCourseGroups(List<CourseGroup> courses)
    {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        courses.forEach((course) -> {
            model.addElement(course);
        });
        this.cmbCourseGroups.setModel(model);
    }

    public void setController(FingerprintController controller)
    {
        this.fingerprintController = controller;
    }
    
    /**
     * Show message in textArea
     * 
     * @param string
     */
    public void showMessage(String string) {
        txtAreaHistory.append(string + "\n");
    }
    
    public void getTemplateSuccessful() {
        //btnIdentify.setEnabled(true);
        btnSave.setEnabled(true);
        btnSave.grabFocus();
    }

    public void showErrorMessage(String msg) {
        JOptionPane.showMessageDialog(
            FingerprintForm.this,
            msg,
            "Action failed",
            JOptionPane.ERROR_MESSAGE
        );
    }
    
    public void showInfoMessage(String msg) {
        JOptionPane.showMessageDialog(
            FingerprintForm.this,
            msg,
            "Action info",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public void showSuccessfulMessage(String msg) {
        JOptionPane.showMessageDialog(
            FingerprintForm.this,
            msg,
            "Action was successful",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    public CourseGroup getCourseSelected() {
        return (CourseGroup) this.cmbCourseGroups.getModel().getSelectedItem();
    }
    
    public void enableBtnStop(Boolean value){
        this.btnStop.setEnabled(value);
    }
    
    public void enableBtnParticipations(Boolean value){
        this.btnRegisterParticipation.setEnabled(value);
    }
    
    public void enableBtnAssistance(Boolean value){
        this.btnRegisterAssistance.setEnabled(value);
    }
    
    public void enableBtnSave(Boolean value){
        this.btnSave.setEnabled(value);
    }
    
    public void enableBtnIdentify(Boolean value){
        //this.btnIdentify.setEnabled(value);
    }
    
    public void enableCmbCourseGroups(Boolean value){
        this.cmbCourseGroups.setEnabled(value);
    }
    
    public void setTitleText(String str){
        this.lblTitle.setText(str);
    }
    
    public void formWindowClosing() {
        this.fingerprintController.stop();
        showMessage("Fingerprint is not being used");
    }
    
    /**
     *
     * @param image
     */
    public void drawFingerprint(Image image) {
        
        ImageIcon imageIcon = new ImageIcon(
            image.getScaledInstance(
                    lblFingerprintImage.getWidth(),
                    lblFingerprintImage.getHeight(),
                    Image.SCALE_DEFAULT
            )
        );
        lblFingerprintImage.setIcon(imageIcon);
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFingerprint = new javax.swing.JPanel();
        lblFingerprintImage = new javax.swing.JLabel();
        lblTitleFingerprintImage = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        cmbCourseGroups = new javax.swing.JComboBox<>();
        btnRegisterParticipation = new javax.swing.JButton();
        btnRegisterAssistance = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        panelHistory = new javax.swing.JPanel();
        scrollHistory = new javax.swing.JScrollPane();
        txtAreaHistory = new javax.swing.JTextArea();
        lblTitleHistory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAS BIOMETRIC FINGERPRINT");
        setMinimumSize(new java.awt.Dimension(685, 490));

        panelFingerprint.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitleFingerprintImage.setText("Digital Fingerprint");

        javax.swing.GroupLayout panelFingerprintLayout = new javax.swing.GroupLayout(panelFingerprint);
        panelFingerprint.setLayout(panelFingerprintLayout);
        panelFingerprintLayout.setHorizontalGroup(
            panelFingerprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFingerprintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFingerprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFingerprintImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitleFingerprintImage, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFingerprintLayout.setVerticalGroup(
            panelFingerprintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFingerprintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleFingerprintImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFingerprintImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CourseGroup Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnSave.setText("Save Fingerprint");
        btnSave.setToolTipText("Asignar huella a un estudiante");
        btnSave.setPreferredSize(new java.awt.Dimension(160, 30));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbCourseGroups.setPreferredSize(new java.awt.Dimension(75, 30));
        cmbCourseGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseGroupsActionPerformed(evt);
            }
        });

        btnRegisterParticipation.setText("Register Participation");
        btnRegisterParticipation.setPreferredSize(new java.awt.Dimension(160, 30));
        btnRegisterParticipation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterParticipationActionPerformed(evt);
            }
        });

        btnRegisterAssistance.setText("Register Assistance");
        btnRegisterAssistance.setPreferredSize(new java.awt.Dimension(160, 30));
        btnRegisterAssistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAssistanceActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 51, 51));
        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.setText("Stop");
        btnStop.setPreferredSize(new java.awt.Dimension(160, 30));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lblTitle.setText("WELCOME TO DAS BF");

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelButtonsLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegisterAssistance, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelButtonsLayout.createSequentialGroup()
                        .addComponent(cmbCourseGroups, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegisterParticipation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCourseGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterParticipation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterAssistance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelHistory.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollHistory.setAutoscrolls(true);

        txtAreaHistory.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtAreaHistory.setLineWrap(true);
        txtAreaHistory.setBorder(null);
        scrollHistory.setViewportView(txtAreaHistory);

        lblTitleHistory.setText("History");

        javax.swing.GroupLayout panelHistoryLayout = new javax.swing.GroupLayout(panelHistory);
        panelHistory.setLayout(panelHistoryLayout);
        panelHistoryLayout.setHorizontalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHistoryLayout.createSequentialGroup()
                        .addComponent(scrollHistory)
                        .addContainerGap())
                    .addGroup(panelHistoryLayout.createSequentialGroup()
                        .addComponent(lblTitleHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))))
        );
        panelHistoryLayout.setVerticalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelFingerprint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFingerprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.fingerprintController.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnRegisterAssistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAssistanceActionPerformed
        this.fingerprintController.enableAssistances();
    }//GEN-LAST:event_btnRegisterAssistanceActionPerformed

    private void btnRegisterParticipationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterParticipationActionPerformed
        this.fingerprintController.enableParticipations();
    }//GEN-LAST:event_btnRegisterParticipationActionPerformed

    private void cmbCourseGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseGroupsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        this.fingerprintController.enableSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FingerprintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FingerprintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FingerprintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FingerprintForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FingerprintForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterAssistance;
    private javax.swing.JButton btnRegisterParticipation;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cmbCourseGroups;
    private javax.swing.JLabel lblFingerprintImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleFingerprintImage;
    private javax.swing.JLabel lblTitleHistory;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelFingerprint;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JScrollPane scrollHistory;
    private javax.swing.JTextArea txtAreaHistory;
    // End of variables declaration//GEN-END:variables
}
